---
title: "Untitled"
author: "Nadege Belouard"
date: "4/11/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Setup
```{r setup for rendering, include = F, messages = F, warning = F}

# attaching necessary packages
library(tidyverse)
library(magrittr)
library(sf)
library(maps)
library(DescTools)
library(reshape2)
library(ggplot2)
library(here)
library(slfjumps)
library(leaflet)

sf::sf_use_s2(FALSE)
```

# Load data


# Figure 4: boxplot distance to transports
```{r plot histogram of distances between jumpers, diffusers, undetected, fig.height=5, fig.width = 6, fig.cap="Distance of jumpers, diffusers and non-detections to railroads (top), roads (middle), and airports (bottom). The y axis is truncated to better show the boxes. Refer to section 1 for variables summary."}

slf_uptodate <- read.csv(file.path(here(), "exported-data", "slf_obs_uptodate.csv"))
head(slf_uptodate)

#Modify dataset to get distribution of distances with a column for the type of distance (Road, Rail...), and one column for the type of dataset (Full or Rarefied)
slf_uptodate_long <- slf_uptodate %>% 
  pivot_longer(cols = starts_with("Dist"), names_to = "DistanceType", values_to = "DistanceValue")

# Order the variables (for plots)
unique(slf_uptodate_long$Category_full)
slf_uptodate_long$Category_full <- factor(slf_uptodate_long$Category_full, levels = c("Jumpers", "Diffusers", "Negatives"))

unique(slf_uptodate_long$Category_rare)
slf_uptodate_long$Category_rare <- factor(slf_uptodate_long$Category_rare, levels = c("Jumpers", "Diffusers", "Negatives"))

slf_uptodate_long$DistanceType <- factor(slf_uptodate_long$DistanceType, levels = c("DistToRoad", "DistToRail", "DistIntRlRd"))

slf_uptodate_long %>% group_by(Category_rare, DistanceType) %>% count()

slf_uptodate_long %>% mutate(Category_full = recode(Category_full, "Jumpers" = "Jump points",
                                                    "Diffusers" = "Diffusion points",
                                                    "Negatives" = "Negative points"),
                             Category_rare = recode(Category_rare, "Jumpers" = "Jump points",
                                                    "Diffusers" = "Diffusion points",
                                                    "Negatives" = "Negative points"))


# Plot distances (full dataset)
transport_bpfull <- ggplot(slf_uptodate_long, aes(y = DistanceValue/1000, x = Category_full)) + 
  geom_boxplot(aes(fill = Category_full), 
               show.legend = F,
               # outlier.shape = NA
               ) +
  scale_fill_manual(values = c("white", "lightgray", "grey30")) +
  facet_wrap(~DistanceType, scales = "free_y", ncol = 4, 
             labeller = labeller(DistanceType = 
    c("DistToRail" = "Railroad",
      "DistToRoad" = "Major road",
      "DistIntRlRd" = "Intersection of railroads and roads"))) +
  # coord_cartesian(ylim=c(0, 16)) +
  xlab(NULL) + ylab("Distance to the nearest... (km)") +
  theme_classic() +
  ggtitle("(A) Full dataset") +
  theme(axis.text.x=element_blank())

transport_bpfull

ggsave(file.path(here(), "figures", "jump_transports", "1bis. boxplot transport_fulldata_v2.jpg"), transport_bp, width = 7, height = 2.5)


# Plot distances (rarefied dataset)
transport_bprare <- ggplot(slf_uptodate_long, aes(y = DistanceValue/1000, x = Category_rare)) + 
  geom_boxplot(aes(fill = Category_rare), show.legend = F) +
  scale_fill_manual(values = c("white", "lightgray", "grey30")) +
  facet_wrap(~DistanceType, scales = "free_y", ncol = 4,
              labeller = labeller(DistanceType =
    c("DistToRail" = "Railroad",
      "DistToRoad" = "Major road",
      "DistIntRlRd" = "Intersection of railroads and roads"))) +
  xlab(NULL) + ylab("Distance to the nearest... (km)") +
  theme_classic() +
  ggtitle("(B) Rarefied dataset")

transport_bp

ggsave(file.path(here(), "figures", "jump_transports", "2bis. boxplot transport_rarefieddata_v2.jpg"), transport_bp, width = 7, height = 2.5)

library(gridExtra)
figure <- grid.arrange(transport_bpfull, transport_bprare)
ggsave(file.path(here(), "figures", "jump_transports", "3. boxplot transport.jpg"), figure, width = 7, height = 5)

```

